---
#ansible-playbook createDataSript.yml
- hosts: localhost
  connection: local
  vars:
    controller: 10.91.55.10
    username: admin
    password: Avi123$%
    api_version: 17.2.7
    name: CV1-hosts
    tenant: admin
    pool_name: pool1

  roles:
    - role: avinetworks.avisdk

  tasks:
    - name: "Create Data Script - {{ name }}"
      avi_vsdatascriptset:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        avi_api_update_method: patch
        avi_api_patch_op: add
        name: "{{ name }}"
        tenant_ref: "/api/tenant/?name={{ tenant }}"
        pool_refs:
        - "/api/pool/?name={{ pool_name }}"
