---
#ansible-playbook configCloud.yml -e "controller=10.10.29.250"
- hosts: localhost
  connection: local
  vars:
    controller: 10.91.55.10
    username: admin
    password: Avi123$%
    api_version: 17.2.7
    vcenter_url: "10.10.2.10"
    vcenter_user: root
    vcenter_pwd: vmware
    tenant: admin
    discovery_time: 120
    vmware_cloud_name: vmwarecloud
    cloud_datacenter: 10GTest
    old_password: 58NFaGDJm(PJH0G
    vmware_cluster_name: Arista
    vm_mgmt_nw_name: PG-1055
    vm_mgmt_nw_addr: 10.91.55.0
    vm_mgmt_maskbits: 24
    vm_mgmt_begin_addr: 10.91.55.100
    vm_mgmt_end_addr: 10.91.55.200
    vm_mgmt_dg: 10.91.55.1

    vrf_gw_mon_ip: 10.91.29.1
    vrf_name: VRF-GSLB
    prefix_name: luiz
    vcenter_folder: luiz
    network_name: PG-1029
    net_address: 10.91.29.0
    net_maskbits: 24
    beg_addr: 10.91.29.101
    end_addr: 10.91.29.250
    service_engine_group_name: SEGGSLB


  roles:
    - { role: avinetworks.avicontroller-vmware }
    - { role: avinetworks.avisdk }

  tasks:
    - name: defining avi config for Cloud Connector
      set_fact:
        avi_config_cloud:
          # Cloud connector config
          avi_cloud_discovery_wait: "{{ discovery_time }}"
          cloud:
            - name: "{{ vmware_cloud_name }}"
              vtype: CLOUD_VCENTER
              tenant_ref: '/api/tenant/?name={{ tenant }}'
              dhcp_enabled: false
              license_type: "LIC_CORES"
              vcenter_configuration:
                username: "{{ vcenter_user }}"
                password: "{{ vcenter_pwd }}"
                datacenter: "{{ cloud_datacenter }}"
                management_network: "/api/vimgrnwruntime/?name={{ vm_mgmt_nw_name }}"
                privilege: "WRITE_ACCESS"
                vcenter_url: "{{ vcenter_url }}"
                management_ip_subnet:
                    mask: "{{ vm_mgmt_maskbits }}"
                    ip_addr:
                        type: V4
                        addr: "{{ vm_mgmt_nw_addr }}"

    - name: Configuring the cloud connector
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_credentials:
          controller: "{{ controller }}"
          username: "{{ username }}"
          password: "{{ password }}"
          api_version: "{{ api_version }}"
        avi_config: "{{ avi_config_cloud }}"
