---
#ansible-playbook configCloud.yml -e "controller=10.10.29.250"
- hosts: localhost
  connection: local

  roles:
    - { role: avinetworks.avicontroller-vmware }
    - { role: avinetworks.avisdk }

  tasks:
    - name: defining avi config for Cloud Connector
      set_fact:
        avi_config_cloud:
          # Cloud connector config
          avi_cloud_discovery_wait: "{{ discovery_time }}"
          cloud:
            - name: "{{ vmware_cloud_name }}"
              vtype: CLOUD_VCENTER
              tenant_ref: '/api/tenant/?name={{ vmware_tenant }}'
              dhcp_enabled: false
              license_type: "LIC_CORES"
              vcenter_configuration:
                username: "{{ vcenter_user }}"
                password: "{{ vcenter_pwd }}"
                datacenter: "{{ vmware_connector_datacenter }}"
                management_network: "/api/vimgrnwruntime/?name={{ vm_mgmt_nw_name }}"
                privilege: "WRITE_ACCESS"
                vcenter_url: "{{ vcenter_url }}"
                management_ip_subnet:
                    mask: "{{ vm_mgmt_maskbits }}"
                    ip_addr:
                        type: V4
                        addr: "{{ vm_mgmt_nw_addr }}"

    - name: Configuring the cloud connector
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_credentials:
          controller: "{{ controller }}"
          username: "{{ username }}"
          password: "{{ password }}"
          api_version: "{{ api_version }}"
        avi_config: "{{ avi_config_cloud }}"
