---
#ansible-playbook configGSLB.yml -e "controller=10.10.29.250"
- hosts: localhost
  connection: local

  roles:
    - role: avinetworks.avisdk

  tasks:
    # Configure GSLB VS and site
    - name: "Check if user {{ gslb_username }} exists on Avi"
      avi_api_session:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        http_method: get
        path: user
        params:
          name: "{{ gslb_username }}"
      register: user_exists

#    - name: Existing User
#      debug: msg="{{ user_exists }}"

    - name: "If user {{ gslb_username }} doesn't exist create it on Avi"
      avi_api_session:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        http_method: post
        path: user
        data:
          name: "{{ gslb_username}}"
          username: "{{ gslb_username }}"
          password: "{{ gslb_password}}"
          access:
            - role_ref: "/api/role?name=System-Admin"
              tenant_ref: "/api/tenant?name={{ gslb_tenant }}"
          user_profile_ref: "/api/useraccountprofile?name=No-Lockout-User-Account-Profile"
      when: user_exists.obj.count == 0

    - name: Create GSLB VS "{{ vs_name }}"
      avi_virtualservice:
        controller: "{{ controller }}"
        username: "{{ username }}"
        password: "{{ password }}"
        api_version: "{{ api_version }}"
        avi_api_update_method: patch
        avi_api_patch_op: add
        name: "{{ vs_name }}"
        services:
            - port: "{{ port_num }}"
        application_profile_ref: '/api/applicationprofile?name=System-DNS'
        vrf_context_ref: "/api/vrfcontext/?name={{ vs_vrf_name }}"
        tenant_ref: "/api/tenant/?name={{ gslb_tenant }}"
        cloud_ref: "/api/cloud?name={{ vs_vmware_cloud_name }}"
        se_group_ref: "/api/serviceenginegroup/?name={{ vs_SEG_name }}"
        vip:
            -
              vip_id: 0
              subnet:
                mask: "{{ vip_netmask_bits }}"
                ip_addr:
                  type: V4
                  addr: "{{ vip_network_address }}"
              ip_address:
                  type: V4
                  addr: "{{ vs_ip }}"
              network_ref: '/api/network/?name={{ network_name }}'
              discovered_networks:
                -
                    subnet:
                        -
                            mask: "{{ vs_ip_netmask_bits }}"
                            ip_addr:
                                type: V4
                                addr: "{{ vs_ip_network_address }} "
                    network_ref: '/api/network/?name={{ vs_network_name }}'

    - name: Get VS info "{{ vs_name }}"
      avi_api_session:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        http_method: get
        path: virtualservice
        params:
          name: "{{ vs_name }}"
      register: vs_info

    - name: Get main Cluster Information using avi_api_session
      avi_api_session:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        http_method: get
        path: cluster
      register: cluster_info
      
    - name: Create GSLB
      avi_gslb:
        username: "{{ username }}"
        password: "{{ password }}"
        controller: "{{ controller }}"
        api_version: "{{ api_version }}"
        sites:
        - enabled: true
          port: 443
          member_type: GSLB_ACTIVE_MEMBER
          cluster_uuid: "{{ cluster_info['obj'].uuid }}"
          ip_addresses:
          - type: V4
            addr: "{{ gslb_controller }}"
          dns_vses:
                -
                    dns_vs_uuid: "{{ vs_info['obj']['results'][0]['uuid'] }}"
                    domain_names: []
          name: "{{ sitename }}"
          username: "{{ gslb_username }}"
          password: "{{ gslb_password }}"
        send_interval: 30
        name: "{{ gslb_sitename }}"
        dns_configs:
        - domain_name: "{{ gslb_domain }}"
        leader_cluster_uuid: "{{ cluster_info['obj'].uuid }}"
        third_party_sites:
          - 
            enabled: true
            name: "{{ gslb_sitename }}_outside"
            hm_proxies:
              - 
                site_uuid: "{{ cluster_info['obj'].uuid }}"