---
#ansible-playbook configAdminNetwork.yml -e "controller=10.91.55.10"
- hosts: localhost
  connection: local

  tasks:
    # VRF for admin cloud connectro
    - name: Config Admin VRF
      avi_vrfcontext:
        avi_credentials:
          controller: "{{ controller }}"
          username: "{{ username }}"
          password: "{{ password }}"
          api_version: "{{ api_version }}"
        name: global
        avi_api_update_method: patch
        avi_api_patch_op: add
        system_default: true
        cloud_ref: "/api/cloud/?name={{ vmware_cloud_name }}"
        tenant_ref: "/api/tenant/?name={{ vmware_tenant }}"
        static_routes:
        - cloud_ref:  "/api/cloud/?name={{ vmware_cloud_name }}"
          system_default: false
          next_hop:
            addr: "{{ vm_mgmt_dg }}"
            type: V4
          prefix_text: 0.0.0.0/0
          prefix:
            ip_addr:
              addr: 0.0.0.0
              type: V4
            mask: '0'
          route_id: '1'

    # Network for admin Cloud
    - name: Config Admin Network
      avi_network:
        avi_credentials:
          controller: "{{ controller }}"
          username: "{{ username }}"
          password: "{{ password }}"
          api_version: "{{ api_version }}"
        name: "{{ vm_mgmt_nw_name }}"
        vrf_context_ref: "/api/vrfcontext/?name=global"
        tenant_ref: "/api/tenant/?name={{ vmware_tenant }}"
        cloud_ref: "/api/cloud/?name={{ vmware_cloud_name }}"
        configured_subnets:
          - prefix:
              ip_addr:
                type: V4
                addr: "{{ vm_mgmt_nw_addr }}"
              mask: "{{ vm_mgmt_maskbits }}"
            static_ranges:
            - begin:
                type: V4
                addr: "{{ vm_mgmt_begin_addr }}"
              end:
                type: V4
                addr: "{{ vm_mgmt_end_addr }}"
        exclude_discovered_subnets: false
        dhcp_enabled: false
#        vcenter_dvs: true
