---
#ansible-playbook deployControllers.yml -e "mgmt_ip=10.91.55.11 vm_name=luiz-0-gslb-cluster-ctrl"&
#ansible-playbook deployControllers.yml -e "mgmt_ip=10.91.56.11 vm_name=luiz-1-gslb-cluster-ctrl"&
#ansible-playbook deployControllers.yml -e "mgmt_ip=10.91.57.11 vm_name=luiz-2-gslb-cluster-ctrl"&
- hosts: localhost
  connection: local
  roles:
    - { role: avinetworks.avicontroller-vmware }
    - { role: avinetworks.avisdk }

  tasks:
    - name: Include vars
      include_vars:
        file: vars/env_vars.yml
        
    - name: Deploy Avi Controller "{{ vm_name }}"
      deploy_controller:
        state: "{{ state | default('present')}}"
        ovftool_path: /usr/bin/
        vcenter_host: "{{ vcenter_host }}"
        vcenter_user: "{{ vcenter_user }}"
        vcenter_password: "{{ vcenter_pwd }}"
        con_datacenter: "{{ vmware_datacenter }}"
        con_cluster: "{{ vmware_cluster }}"
        con_ova_path: "{{ ova_path }}"
        con_vm_name: "{{ vm_name }}"
        con_vcenter_folder: "{{ vcenter_folder }}"
        con_datastore: "{{ vmware_datastore }}"
        con_mgmt_network: "{{ controller_mgmt_network }}"
        con_power_on: "{{ power_on }}"
        con_mgmt_ip: "{{ mgmt_ip }}"
        con_mgmt_mask: "{{ mgmt_mask }}"
        con_default_gw: "{{ default_gw }}"
        #con_number_of_cpus: 16
        #con_memory: 32
        #con_disk_size: 500
