#ansible-playbook creadePool.yml
- hosts: 10.91.55.5
  connection: local
  ansible_connection: ssh 
  ansible_ssh_user: admin 
  ansible_ssh_pass: Avi123$%

  tasks:
    - name: Copy upgrade file
      copy:
        src: ../../17.2.11-1p1/controller_patch.pkg
        dest: /var/lib/avi/upgrade_pkgs/controller.pkg
